package com.cretihoy.wordminded

object CardFactory {

    fun getLetters(): List<CardModel> {
        return listOf(
            CardModel(content = R.string.letter_1),
            CardModel(content = R.string.letter_1_1),
            CardModel(content = R.string.letter_2),
            CardModel(content = R.string.letter_2_1),
            CardModel(content = R.string.letter_3),
            CardModel(content = R.string.letter_3_1),
            CardModel(content = R.string.letter_4),
            CardModel(content = R.string.letter_4_1),
            CardModel(content = R.string.letter_5),
            CardModel(content = R.string.letter_5_1),
            CardModel(content = R.string.letter_6),
            CardModel(content = R.string.letter_6_1),
            CardModel(content = R.string.letter_7),
            CardModel(content = R.string.letter_7_1),
            CardModel(content = R.string.letter_8),
            CardModel(content = R.string.letter_8_1),
            CardModel(content = R.string.letter_9),
            CardModel(content = R.string.letter_9_1),
            CardModel(content = R.string.letter_10),
            CardModel(content = R.string.letter_10_1),
            CardModel(content = R.string.letter_11),
            CardModel(content = R.string.letter_11_1),
            CardModel(content = R.string.letter_12),
            CardModel(content = R.string.letter_12_1),
            CardModel(content = R.string.letter_13),
            CardModel(content = R.string.letter_13_1),
            CardModel(content = R.string.letter_14),
            CardModel(content = R.string.letter_14_1),
            CardModel(content = R.string.letter_15),
            CardModel(content = R.string.letter_15_1),
            CardModel(content = R.string.letter_16),
            CardModel(content = R.string.letter_16_1),
            CardModel(content = R.string.letter_17),
            CardModel(content = R.string.letter_17_1),
            CardModel(content = R.string.letter_18),
            CardModel(content = R.string.letter_18_1),
            CardModel(content = R.string.letter_19),
            CardModel(content = R.string.letter_19_1),
            CardModel(content = R.string.letter_20),
            CardModel(content = R.string.letter_20_1),
            CardModel(content = R.string.letter_21),
            CardModel(content = R.string.letter_21_1),
            CardModel(content = R.string.letter_22),
            CardModel(content = R.string.letter_22_1),
            CardModel(content = R.string.letter_23),
            CardModel(content = R.string.letter_23_1),
            CardModel(content = R.string.letter_24),
            CardModel(content = R.string.letter_24_1),
            CardModel(content = R.string.letter_25),
            CardModel(content = R.string.letter_25_1),
            CardModel(content = R.string.letter_26),
            CardModel(content = R.string.letter_26_1)
        )
    }
}